/*
 * Copyright (C) 2022 Henrique Pereira/Hlcpereira
 *
 * This file has been auto generated by the .NET Core CLI and modified
 * All the changes made are under the license below.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

using Microsoft.OpenApi.Models;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

var services = builder.Services;

services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
services.AddEndpointsApiExplorer();
services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("General Github", new OpenApiInfo { Title = "General Github", Version = "v1" });
    }
);
services.AddSwaggerGen(c =>
{
    c.CustomSchemaIds(type => type.ToString());
});

var app = builder.Build();
var env = app.Environment;

// Configure the HTTP request pipeline.
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("Issues", new OpenApiInfo { Title = "Issues Github", Version = "v1" });
}
);

app.UseAuthorization();

app.MapControllers();

app.Run();
